name: clone
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest]
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: checkout target
        uses: actions/checkout@v3
        with:
          repository: chm-diederichs/action-test-target
          token: ${{ secrets.TRIGGER_GITHUB_TOKEN }}
          path: target
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: run target
        run: |
          echo $PWD
          ls
          cd target
          npm i $GITHUB_WORKSPACE
          npm test
