name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest]
    timeout-minutes: 30
    steps:
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: git clone git@github.com:chm-diederichs/actions-test-target
      - run: cd actions-test-target
      - run: npm install
      - run: npm install chm-diederichs/actions-test-trigger
      - run: npm test
