name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: keet-core
        with:
          github-token: ${{ secrets.TRIGGER_GITHUB_TOKEN }}
        run: |
          git clone chm-diederichs/action-test-target.git
          npm i
          npm i chm-diederichs/actions-test-trigger
          npm test
